require("harpoon").setup()

local ui = require("harpoon.ui")
local mark = require("harpoon.mark")

local options = { noremap = true, silent = true }

vim.keymap.set("n", "<C-e>", function()
	ui.toggle_quick_menu()
end, options)
vim.keymap.set("n", "<leader>a", function()
	mark.add_file()
end, options)

vim.keymap.set("n", "<C-h>", function()
	ui.nav_file(1)
end, options)
vim.keymap.set("n", "<C-j>", function()
	ui.nav_file(2)
end, options)
vim.keymap.set("n", "<C-k>", function()
	ui.nav_file(3)
end, options)
vim.keymap.set("n", "<C-l>", function()
	ui.nav_file(4)
end, options)

vim.keymap.set("n", "<leader>1", function()
	ui.nav_file(1)
end, options)
vim.keymap.set("n", "<leader>2", function()
	ui.nav_file(2)
end, options)
vim.keymap.set("n", "<leader>3", function()
	ui.nav_file(3)
end, options)
vim.keymap.set("n", "<leader>4", function()
	ui.nav_file(4)
end, options)
vim.keymap.set("n", "<leader>5", function()
	ui.nav_file(5)
end, options)
vim.keymap.set("n", "<leader>6", function()
	ui.nav_file(6)
end, options)
vim.keymap.set("n", "<leader>7", function()
	ui.nav_file(7)
end, options)
vim.keymap.set("n", "<leader>8", function()
	ui.nav_file(8)
end, options)
vim.keymap.set("n", "<leader>9", function()
	ui.nav_file(9)
end, options)
