#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Application specific configuration
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Colorpicker" manage=off
yabai -m rule --add app="Archive Utility" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="1Password 7" manage=off
yabai -m rule --add app="Alfred Preferences" manage=off
yabai -m rule --add app="^Font book" manage=off

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "Fira Code Nerd Font Mono:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  1 2 3 4 5 6
# yabai -m config status_bar_power_icon_strip  ? ?
# yabai -m config status_bar_space_icon        ?
# yabai -m config status_bar_clock_icon        ?

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.

yabai -m config window_border                on 
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xffff0000
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   05

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main:25:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:25:0

source ~/.config/yabai/simplebar.sh

echo "yabai configuration loaded.."

# kill any existing limelight process if one exists, before we launch a new one
# killall limelight &> /dev/null
# limelight -c ~/.config/limelight/limelightrc &> /dev/null &
