#!/usr/bin/env bash

find ~/workspace/playground \
  ~/Workspace/go \
  ~/Workspace/docker \
  ~/Workspace/repositories/github.com/appsfortableau \
  ~/Workspace/repositories/github.com/yoramdelangen \
  ~/Workspace/repositories/github.com/writebackextreme \
  -mindepth 1 -maxdepth 1 -type d | fzf
